'use strict';

if (typeof toolbox_custom == 'undefined')
  var toolbox_custom = [];

toolbox_custom.push(''
+'  <category name="小車ESP32" colour="#5ba58c">'
+'    <block type="imi_esp32car_init">'
+'      <value name="uart">'
+'        <block type="imi_esp32car_init_uart">'
+'          <value name="rx">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="tx">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'      <value name="wifi">'
+'        <block type="imi_esp32car_init_wifi">'
+'          <value name="ssid">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'          <value name="wifi_pwd">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'      <value name="line">'
+'        <block type="imi_esp32car_init_line">'
+'          <value name="line_token">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'      <value name="mqtt">'
+'        <block type="imi_esp32car_init_mqtt">'
+'          <value name="mqtt_user">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'          <value name="mqtt_pwd">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'          <value name="mqtt_port">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="mqtt_server">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'    </block>'
+'    <block type="imi_esp32car_loop"></block>'
+'    <block type="imi_esp32car_getarduino_func"></block>'
+'    <block type="imi_esp32car_submqtt">'
+'      <field name="mqtt_topic">TOPIC_MAP_SET</field>'
+'    </block>'
+'    <block type="imi_esp32car_mqttcallback_func"></block>'
+'    <block type="imi_esp32car_ismqtttopic">'
+'      <field name="mqtt_topic">TOPIC_MAP_SET</field>'
+'    </block>'
+'    <block type="imi_esp32car_sendarduino_mapset"></block>'
+'    <block type="imi_esp32car_pubmqtt_carstandby"></block>'
+'    <block type="imi_esp32car_sendarduino_goodsload"></block>'
+'    <block type="imi_esp32car_isarduinomsg">'
+'      <field name="uart_topic">MAP_SET</field>'
+'    </block>'
+'    <block type="imi_esp32car_getarduino_recipient"></block>'
+'    <block type="imi_esp32car_line_recipient"></block>'
+'    <block type="imi_esp32car_getarduino_gps"></block>'
+'    <block type="imi_esp32car_pubmqtt_cargps"></block>'
+'  </category>');