#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/02fbe424-1577-4ccc-99b4-7766e47954c4 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLocation coordinates;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

//UART
#define U1RXD 16
#define U1TXD 17

double  Lats[4][6]={
  {22.6364582999265,	22.6364582999265,	22.6364582999265,	22.6364582999265,	22.6364582999265,	22.6364582999265},
  {22.6349390408069,	22.6349390408069,	22.6349390408069,	22.6349390408069,	22.6349390408069,	22.6349390408069},
  {22.6334197816872,	22.6334197816872,	22.6334197816872,	22.6334197816872,	22.6334197816872,	22.6334197816872},
  {22.6319005225676,	22.6319005225676,	22.6319005225676,	22.6319005225676,	22.6319005225676,	22.6319005225676}
};

double  Longs[4][6]={
  {120.30257035839 , 120.304121598992, 120.305672839593 , 120.307224080195 , 120.308775320796 , 120.310326561398},
  {120.30257035839 , 120.304121598992, 120.305672839593 , 120.307224080195 , 120.308775320796 , 120.310326561398},
  {120.30257035839 , 120.304121598992, 120.305672839593 , 120.307224080195 , 120.308775320796 , 120.310326561398},
  {120.30257035839 , 120.304121598992, 120.305672839593 , 120.307224080195 , 120.308775320796 , 120.310326561398}
};

int carX = 0;
int carY = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  Serial2.begin(9600, SERIAL_8N1, U1RXD, U1TXD);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  
  String str = Serial2.readString();
  if(str !=""){
    carX = (int)(str.charAt(0) - '0');
    carY = (int)(str.charAt(1) - '0');
  
    Serial.println(carX);
    Serial.println(carY);
  
    coordinates = {Lats[carX][carY], Longs[carX][carY]};
  }  
  
}//end loop










