'use strict';

if (typeof toolbox_custom == 'undefined')
  var toolbox_custom = [];

toolbox_custom.push(''
+'  <category name="小車Mega" colour="#5ba55b">'
+'    <block type="_01imi_megacar_init" >'
+'      <statement name="uart">'
+'        <block type="_02imi_megacar_init_uart" >'
+'          <value name="rx">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="tx">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'      <statement name="track">'
+'        <block type="_03imi_megacar_init_track" >'
+'          <value name="left">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="front">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="back">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="right">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'      <statement name="trig">'
+'        <block type="_04imi_megacar_init_trig" >'
+'          <value name="trig">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'      <statement name="carbox">'
+'        <block type="_05imi_megacar_init_carbox" >'
+'          <value name="carbox">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="open">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="close">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'      <statement name="aicam">'
+'        <block type="_06imi_megacar_init_aicam" >'
+'          <value name="aicam">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="front">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="up">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'      <statement name="sign">'
+'        <block type="_07imi_megacar_init_sign" >'
+'          <value name="sign">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'      <statement name="l298n">'
+'        <block type="_08imi_megacar_init_l298n" >'
+'          <value name="in1">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="in2">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="in3">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="in4">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="in5">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="in6">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="in7">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="in8">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'      <statement name="l298n2">'
+'        <block type="_09imi_megacar_init_l298n2" >'
+'          <value name="en1">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="en2">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="en3">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="en4">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </statement>'
+'    </block>'
+'    <block type="_10imi_megacar_astar" ></block>'
+'    <block type="_11imi_megacar_esp32" ></block>'
+'    <block type="_12imi_megacar_isesp32msg" >'
+'      <field name="msg">MAP_SET</field>'
+'    </block>'
+'    <block type="_13imi_megacar_servo" >'
+'      <field name="servo">servoCarBox</field>'
+'      <field name="angle">ANGLE_CAR_BOX_OPEN</field>'
+'    </block>'
+'    <block type="_14imi_megacar_savemap" ></block>'
+'    <block type="_15imi_megacar_savereci" ></block>'
+'    <block type="_16imi_megacar_startastar" >'
+'      <field name="point">GOODS_POINT</field>'
+'    </block>'
+'    <block type="_17imi_megacar_standbyaicam" ></block>'
+'    <block type="_18imi_megacar_esp32line" ></block>'
+'    <block type="_19imi_megacar_startdetectobject" ></block>'
+'    <block type="_20imi_megacar_isfaceid" >'
+'      <field name="id">FACE_ID1</field>'
+'    </block>'
+'    <block type="_21imi_megacar_currentalgo" >'
+'      <field name="algo">ALGORITHM_OBJECT_RECOGNITION</field>'
+'    </block>'
+'    <block type="_22imi_megacar_issign" ></block>'
+'    <block type="_23imi_megacar_carheadturn" >'
+'      <field name="direct">'U'</field>'
+'    </block>'
+'    <block type="_24imi_megacar_getpower" ></block>'
+'    <block type="_25imi_megacar_islowpower" >'
+'      <field name="percent">0.2</field>'
+'    </block>'
+'    <block type="_26imi_megacar_startcharge" ></block>'
+'    <block type="_27imi_megacar_track_func" ></block>'
+'    <block type="_28imi_megacar_tracksensor" >'
+'      <field name="direct">TRACK_LEFT</field>'
+'    </block>'
+'    <block type="_29imi_megacar_stopfront" >'
+'      <field name="NAME">OPTIONNAME</field>'
+'    </block>'
+'    <block type="_30imi_megacar_direct" >'
+'      <field name="direct">right</field>'
+'    </block>'
+'    <block type="_31imi_megacar_isfindpath" ></block>'
+'    <block type="_32imi_megacar_gocar_func" ></block>'
+'    <block type="_33imi_megacar_aidetect" ></block>'
+'    <block type="_34imi_megacar_trackforward" ></block>'
+'    <block type="_35imi_megacar_esp32gps"></block>'
+'  </category>'
+'');