'use strict';

if (typeof toolbox_custom == 'undefined')
  var toolbox_custom = [];

toolbox_custom.push(''
+'<xml xmlns="https://developers.google.com/blockly/xml" id="toolbox" style="display: none">'
+'  <category name="iMi小車ESP32" colour="#5ba58c">'
+'    <block type="imi_esp32car_pubmqtt_cargps"></block>'
+'    <block type="imi_esp32car_init" deletable="false" movable="false" editable="false">'
+'      <value name="uart">'
+'        <block type="imi_esp32car_init_uart" deletable="false" movable="false" editable="false">'
+'          <value name="rx">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="tx">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'      <value name="wifi">'
+'        <block type="imi_esp32car_init_wifi" deletable="false" movable="false" editable="false">'
+'          <value name="ssid">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'          <value name="wifi_pwd">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'      <value name="line">'
+'        <block type="imi_esp32car_init_line" deletable="false" movable="false" editable="false">'
+'          <value name="line_token">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'      <value name="mqtt">'
+'        <block type="imi_esp32car_init_mqtt" deletable="false" movable="false" editable="false">'
+'          <value name="mqtt_user">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'          <value name="mqtt_pwd">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'          <value name="mqtt_port">'
+'            <block type="math_number">'
+'              <field name="NUM">0</field>'
+'            </block>'
+'          </value>'
+'          <value name="mqtt_server">'
+'            <block type="text">'
+'              <field name="TEXT"></field>'
+'            </block>'
+'          </value>'
+'        </block>'
+'      </value>'
+'    </block>'
+'    <block type="imi_esp32car_loop" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_getarduino_func" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_submqtt" deletable="false" movable="false" editable="false">'
+'      <field name="mqtt_topic">TOPIC_MAP_SET</field>'
+'    </block>'
+'    <block type="imi_esp32car_mqttcallback_func" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_ismqtttopic" deletable="false" movable="false" editable="false">'
+'      <field name="mqtt_topic">TOPIC_MAP_SET</field>'
+'    </block>'
+'    <block type="imi_esp32car_sendarduino_mapset" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_pubmqtt_carstandby" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_sendarduino_goodsload" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_isarduinomsg" deletable="false" movable="false" editable="false">'
+'      <field name="uart_topic">MAP_SET</field>'
+'    </block>'
+'    <block type="imi_esp32car_getarduino_recipient" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_line_recipient" deletable="false" movable="false" editable="false"></block>'
+'    <block type="imi_esp32car_getarduino_gps" deletable="false" movable="false" editable="false"></block>'
+'  </category>'
+'</xml>');